/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "calculadora.h"


void escalares (char *host, int valor1, char operacion, int valor2)
{
	CLIENT *clnt;
	resultado_calculo * result;

#ifndef	DEBUG
	clnt = clnt_create (host, CALCULADORA_PROG, CALCULADORA_VER, "udp");
	if (clnt == NULL) {
		clnt_pcreateerror (host);
		exit (1);
	}
#endif	/* DEBUG */

	if (operacion == '+')
		result = suma_1(valor1, valor2, clnt);
	else if (operacion == '-')
		result = resta_1(valor1, valor2, clnt);
	else if (operacion =='*')
		result = producto_1(valor1, valor2, clnt);
	else if (operacion == '/')
		result = cociente_1(valor1, valor2, clnt);
	else
		perror("Operación inválida.\n");

	if (result == (resultado_calculo *) NULL)
		clnt_perror (clnt, "call failed");

	printf ("El resultado es: %d", result->resultado_calculo_u.resultado);

#ifndef	DEBUG
	clnt_destroy (clnt);
#endif	 /* DEBUG */
}


int
main (int argc, char *argv[])
{
	char *host;

	if (argc < 2) {
		printf ("usage: %s server_host\n", argv[0]);
		exit (1);
	}
	host = argv[1];

	int valor1 = atoi(argv[2]);
	int valor2 = atoi(argv[4]);

	char operacion = *argv[3];

	escalares (host, valor1, operacion, valor2);

	return 0;
}
