/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include <memory.h> /* for memset */
#include "calculadora.h"

/* Default timeout can be changed using clnt_control() */
static struct timeval TIMEOUT = { 25, 0 };

resultado_escalar *
suma_1(int arg1, int arg2,  CLIENT *clnt)
{
	suma_1_argument arg;
	static resultado_escalar clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	arg.arg1 = arg1;
	arg.arg2 = arg2;
	if (clnt_call (clnt, Suma, (xdrproc_t) xdr_suma_1_argument, (caddr_t) &arg,
		(xdrproc_t) xdr_resultado_escalar, (caddr_t) &clnt_res,
		TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&clnt_res);
}

resultado_escalar *
resta_1(int arg1, int arg2,  CLIENT *clnt)
{
	resta_1_argument arg;
	static resultado_escalar clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	arg.arg1 = arg1;
	arg.arg2 = arg2;
	if (clnt_call (clnt, Resta, (xdrproc_t) xdr_resta_1_argument, (caddr_t) &arg,
		(xdrproc_t) xdr_resultado_escalar, (caddr_t) &clnt_res,
		TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&clnt_res);
}

resultado_escalar *
producto_1(int arg1, int arg2,  CLIENT *clnt)
{
	producto_1_argument arg;
	static resultado_escalar clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	arg.arg1 = arg1;
	arg.arg2 = arg2;
	if (clnt_call (clnt, Producto, (xdrproc_t) xdr_producto_1_argument, (caddr_t) &arg,
		(xdrproc_t) xdr_resultado_escalar, (caddr_t) &clnt_res,
		TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&clnt_res);
}

resultado_escalar *
cociente_1(int arg1, int arg2,  CLIENT *clnt)
{
	cociente_1_argument arg;
	static resultado_escalar clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	arg.arg1 = arg1;
	arg.arg2 = arg2;
	if (clnt_call (clnt, Cociente, (xdrproc_t) xdr_cociente_1_argument, (caddr_t) &arg,
		(xdrproc_t) xdr_resultado_escalar, (caddr_t) &clnt_res,
		TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&clnt_res);
}

resultado_vectorial *
sumavec_1(vecx arg1, vecx arg2,  CLIENT *clnt)
{
	sumavec_1_argument arg;
	static resultado_vectorial clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	arg.arg1 = arg1;
	arg.arg2 = arg2;
	if (clnt_call (clnt, SumaVec, (xdrproc_t) xdr_sumavec_1_argument, (caddr_t) &arg,
		(xdrproc_t) xdr_resultado_vectorial, (caddr_t) &clnt_res,
		TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&clnt_res);
}

resultado_vectorial *
restavec_1(vecx arg1, vecx arg2,  CLIENT *clnt)
{
	restavec_1_argument arg;
	static resultado_vectorial clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	arg.arg1 = arg1;
	arg.arg2 = arg2;
	if (clnt_call (clnt, RestaVec, (xdrproc_t) xdr_restavec_1_argument, (caddr_t) &arg,
		(xdrproc_t) xdr_resultado_vectorial, (caddr_t) &clnt_res,
		TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&clnt_res);
}

resultado_vectorial *
productovec_1(vecx arg1, vecx arg2,  CLIENT *clnt)
{
	productovec_1_argument arg;
	static resultado_vectorial clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	arg.arg1 = arg1;
	arg.arg2 = arg2;
	if (clnt_call (clnt, ProductoVec, (xdrproc_t) xdr_productovec_1_argument, (caddr_t) &arg,
		(xdrproc_t) xdr_resultado_vectorial, (caddr_t) &clnt_res,
		TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&clnt_res);
}

resultado_vectorial *
productovecsc_1(vecx arg1, int arg2,  CLIENT *clnt)
{
	productovecsc_1_argument arg;
	static resultado_vectorial clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	arg.arg1 = arg1;
	arg.arg2 = arg2;
	if (clnt_call (clnt, ProductoVecSc, (xdrproc_t) xdr_productovecsc_1_argument, (caddr_t) &arg,
		(xdrproc_t) xdr_resultado_vectorial, (caddr_t) &clnt_res,
		TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&clnt_res);
}

resultado_matricial *
sumamat_1(matx arg1, matx arg2,  CLIENT *clnt)
{
	sumamat_1_argument arg;
	static resultado_matricial clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	arg.arg1 = arg1;
	arg.arg2 = arg2;
	if (clnt_call (clnt, SumaMat, (xdrproc_t) xdr_sumamat_1_argument, (caddr_t) &arg,
		(xdrproc_t) xdr_resultado_matricial, (caddr_t) &clnt_res,
		TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&clnt_res);
}

resultado_matricial *
restamat_1(matx arg1, matx arg2,  CLIENT *clnt)
{
	restamat_1_argument arg;
	static resultado_matricial clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	arg.arg1 = arg1;
	arg.arg2 = arg2;
	if (clnt_call (clnt, RestaMat, (xdrproc_t) xdr_restamat_1_argument, (caddr_t) &arg,
		(xdrproc_t) xdr_resultado_matricial, (caddr_t) &clnt_res,
		TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&clnt_res);
}

resultado_matricial *
productomat_1(matx arg1, matx arg2,  CLIENT *clnt)
{
	productomat_1_argument arg;
	static resultado_matricial clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	arg.arg1 = arg1;
	arg.arg2 = arg2;
	if (clnt_call (clnt, ProductoMat, (xdrproc_t) xdr_productomat_1_argument, (caddr_t) &arg,
		(xdrproc_t) xdr_resultado_matricial, (caddr_t) &clnt_res,
		TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&clnt_res);
}

resultado_matricial *
productomatsc_1(matx arg1, int arg2,  CLIENT *clnt)
{
	productomatsc_1_argument arg;
	static resultado_matricial clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	arg.arg1 = arg1;
	arg.arg2 = arg2;
	if (clnt_call (clnt, ProductoMatSc, (xdrproc_t) xdr_productomatsc_1_argument, (caddr_t) &arg,
		(xdrproc_t) xdr_resultado_matricial, (caddr_t) &clnt_res,
		TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&clnt_res);
}
