/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "calculadora.h"

resultado_calculo *
suma_1_svc(int arg1, int arg2,  struct svc_req *rqstp)
{
	static resultado_calculo  result;

	xdr_free(xdr_resultado_calculo, &result);
	result.resultado_calculo_u.resultado = arg1 + arg2;

	return &result;
}

resultado_calculo *
resta_1_svc(int arg1, int arg2,  struct svc_req *rqstp)
{
	static resultado_calculo  result;

	xdr_free(xdr_resultado_calculo, &result);
	result.resultado_calculo_u.resultado = arg1 - arg2;

	return &result;
}

resultado_calculo *
producto_1_svc(int arg1, int arg2,  struct svc_req *rqstp)
{
	static resultado_calculo  result;

	xdr_free(xdr_resultado_calculo, &result);
	result.resultado_calculo_u.resultado = arg1 * arg2;

	return &result;
}

resultado_calculo *
cociente_1_svc(int arg1, int arg2,  struct svc_req *rqstp)
{
	static resultado_calculo  result;

	xdr_free(xdr_resultado_calculo, &result);
	result.resultado_calculo_u.resultado = arg1 / arg2;

	return &result;
}
