/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "calculadora.h"
#include <stdio.h>
#include <stdlib.h>
#include <rpc/pmap_clnt.h>
#include <string.h>
#include <memory.h>
#include <sys/socket.h>
#include <netinet/in.h>

#ifndef SIG_PF
#define SIG_PF void(*)(int)
#endif

static resultado_escalar *
_suma_1 (suma_1_argument *argp, struct svc_req *rqstp)
{
	return (suma_1_svc(argp->arg1, argp->arg2, rqstp));
}

static resultado_escalar *
_resta_1 (resta_1_argument *argp, struct svc_req *rqstp)
{
	return (resta_1_svc(argp->arg1, argp->arg2, rqstp));
}

static resultado_escalar *
_producto_1 (producto_1_argument *argp, struct svc_req *rqstp)
{
	return (producto_1_svc(argp->arg1, argp->arg2, rqstp));
}

static resultado_escalar *
_cociente_1 (cociente_1_argument *argp, struct svc_req *rqstp)
{
	return (cociente_1_svc(argp->arg1, argp->arg2, rqstp));
}

static resultado_vectorial *
_sumavec_1 (sumavec_1_argument *argp, struct svc_req *rqstp)
{
	return (sumavec_1_svc(argp->arg1, argp->arg2, rqstp));
}

static resultado_vectorial *
_restavec_1 (restavec_1_argument *argp, struct svc_req *rqstp)
{
	return (restavec_1_svc(argp->arg1, argp->arg2, rqstp));
}

static resultado_vectorial *
_productovec_1 (productovec_1_argument *argp, struct svc_req *rqstp)
{
	return (productovec_1_svc(argp->arg1, argp->arg2, rqstp));
}

static resultado_vectorial *
_productovecsc_1 (productovecsc_1_argument *argp, struct svc_req *rqstp)
{
	return (productovecsc_1_svc(argp->arg1, argp->arg2, rqstp));
}

static resultado_matricial *
_sumamat_1 (sumamat_1_argument *argp, struct svc_req *rqstp)
{
	return (sumamat_1_svc(argp->arg1, argp->arg2, rqstp));
}

static resultado_matricial *
_restamat_1 (restamat_1_argument *argp, struct svc_req *rqstp)
{
	return (restamat_1_svc(argp->arg1, argp->arg2, rqstp));
}

static resultado_matricial *
_productomat_1 (productomat_1_argument *argp, struct svc_req *rqstp)
{
	return (productomat_1_svc(argp->arg1, argp->arg2, rqstp));
}

static resultado_matricial *
_productomatsc_1 (productomatsc_1_argument *argp, struct svc_req *rqstp)
{
	return (productomatsc_1_svc(argp->arg1, argp->arg2, rqstp));
}

static void
calculadora_prog_1(struct svc_req *rqstp, register SVCXPRT *transp)
{
	union {
		suma_1_argument suma_1_arg;
		resta_1_argument resta_1_arg;
		producto_1_argument producto_1_arg;
		cociente_1_argument cociente_1_arg;
		sumavec_1_argument sumavec_1_arg;
		restavec_1_argument restavec_1_arg;
		productovec_1_argument productovec_1_arg;
		productovecsc_1_argument productovecsc_1_arg;
		sumamat_1_argument sumamat_1_arg;
		restamat_1_argument restamat_1_arg;
		productomat_1_argument productomat_1_arg;
		productomatsc_1_argument productomatsc_1_arg;
	} argument;
	char *result;
	xdrproc_t _xdr_argument, _xdr_result;
	char *(*local)(char *, struct svc_req *);

	switch (rqstp->rq_proc) {
	case NULLPROC:
		(void) svc_sendreply (transp, (xdrproc_t) xdr_void, (char *)NULL);
		return;

	case Suma:
		_xdr_argument = (xdrproc_t) xdr_suma_1_argument;
		_xdr_result = (xdrproc_t) xdr_resultado_escalar;
		local = (char *(*)(char *, struct svc_req *)) _suma_1;
		break;

	case Resta:
		_xdr_argument = (xdrproc_t) xdr_resta_1_argument;
		_xdr_result = (xdrproc_t) xdr_resultado_escalar;
		local = (char *(*)(char *, struct svc_req *)) _resta_1;
		break;

	case Producto:
		_xdr_argument = (xdrproc_t) xdr_producto_1_argument;
		_xdr_result = (xdrproc_t) xdr_resultado_escalar;
		local = (char *(*)(char *, struct svc_req *)) _producto_1;
		break;

	case Cociente:
		_xdr_argument = (xdrproc_t) xdr_cociente_1_argument;
		_xdr_result = (xdrproc_t) xdr_resultado_escalar;
		local = (char *(*)(char *, struct svc_req *)) _cociente_1;
		break;

	case SumaVec:
		_xdr_argument = (xdrproc_t) xdr_sumavec_1_argument;
		_xdr_result = (xdrproc_t) xdr_resultado_vectorial;
		local = (char *(*)(char *, struct svc_req *)) _sumavec_1;
		break;

	case RestaVec:
		_xdr_argument = (xdrproc_t) xdr_restavec_1_argument;
		_xdr_result = (xdrproc_t) xdr_resultado_vectorial;
		local = (char *(*)(char *, struct svc_req *)) _restavec_1;
		break;

	case ProductoVec:
		_xdr_argument = (xdrproc_t) xdr_productovec_1_argument;
		_xdr_result = (xdrproc_t) xdr_resultado_vectorial;
		local = (char *(*)(char *, struct svc_req *)) _productovec_1;
		break;

	case ProductoVecSc:
		_xdr_argument = (xdrproc_t) xdr_productovecsc_1_argument;
		_xdr_result = (xdrproc_t) xdr_resultado_vectorial;
		local = (char *(*)(char *, struct svc_req *)) _productovecsc_1;
		break;

	case SumaMat:
		_xdr_argument = (xdrproc_t) xdr_sumamat_1_argument;
		_xdr_result = (xdrproc_t) xdr_resultado_matricial;
		local = (char *(*)(char *, struct svc_req *)) _sumamat_1;
		break;

	case RestaMat:
		_xdr_argument = (xdrproc_t) xdr_restamat_1_argument;
		_xdr_result = (xdrproc_t) xdr_resultado_matricial;
		local = (char *(*)(char *, struct svc_req *)) _restamat_1;
		break;

	case ProductoMat:
		_xdr_argument = (xdrproc_t) xdr_productomat_1_argument;
		_xdr_result = (xdrproc_t) xdr_resultado_matricial;
		local = (char *(*)(char *, struct svc_req *)) _productomat_1;
		break;

	case ProductoMatSc:
		_xdr_argument = (xdrproc_t) xdr_productomatsc_1_argument;
		_xdr_result = (xdrproc_t) xdr_resultado_matricial;
		local = (char *(*)(char *, struct svc_req *)) _productomatsc_1;
		break;

	default:
		svcerr_noproc (transp);
		return;
	}
	memset ((char *)&argument, 0, sizeof (argument));
	if (!svc_getargs (transp, (xdrproc_t) _xdr_argument, (caddr_t) &argument)) {
		svcerr_decode (transp);
		return;
	}
	result = (*local)((char *)&argument, rqstp);
	if (result != NULL && !svc_sendreply(transp, (xdrproc_t) _xdr_result, result)) {
		svcerr_systemerr (transp);
	}
	if (!svc_freeargs (transp, (xdrproc_t) _xdr_argument, (caddr_t) &argument)) {
		fprintf (stderr, "%s", "unable to free arguments");
		exit (1);
	}
	return;
}

int
main (int argc, char **argv)
{
	register SVCXPRT *transp;

	pmap_unset (CALCULADORA_PROG, CALCULADORA_VER);

	transp = svcudp_create(RPC_ANYSOCK);
	if (transp == NULL) {
		fprintf (stderr, "%s", "cannot create udp service.");
		exit(1);
	}
	if (!svc_register(transp, CALCULADORA_PROG, CALCULADORA_VER, calculadora_prog_1, IPPROTO_UDP)) {
		fprintf (stderr, "%s", "unable to register (CALCULADORA_PROG, CALCULADORA_VER, udp).");
		exit(1);
	}

	transp = svctcp_create(RPC_ANYSOCK, 0, 0);
	if (transp == NULL) {
		fprintf (stderr, "%s", "cannot create tcp service.");
		exit(1);
	}
	if (!svc_register(transp, CALCULADORA_PROG, CALCULADORA_VER, calculadora_prog_1, IPPROTO_TCP)) {
		fprintf (stderr, "%s", "unable to register (CALCULADORA_PROG, CALCULADORA_VER, tcp).");
		exit(1);
	}

	svc_run ();
	fprintf (stderr, "%s", "svc_run returned");
	exit (1);
	/* NOTREACHED */
}
